/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentProcessingStatus } from '../../models/document-processing-status';

export interface ApiHistoryHideByStatusPost$Params {

/**
 * Status value whose entries should be removed from the history.
 */
  documentProcessingStatus?: DocumentProcessingStatus;
}

export function apiHistoryHideByStatusPost(http: HttpClient, rootUrl: string, params?: ApiHistoryHideByStatusPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiHistoryHideByStatusPost.PATH, 'post');
  if (params) {
    rb.query('documentProcessingStatus', params.documentProcessingStatus, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiHistoryHideByStatusPost.PATH = '/api/history/hideByStatus';
