version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/ArquivoMate2.API/Dockerfile
    ports:
      - "5000:8081"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Host=db;Port=5432;Database=arquivomate;Username=postgres;Password=yourpassword"

  redis:
    image: redis/redis-stack:7.2.0-v8
    volumes:
       - redis:/data
       - redis:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
     - 6379:6379
     - 13333:8001

  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: arquivomate
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - db_data:/var/lib/postgresql/data

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    ports:
      - "127.0.0.1:8070:80"
      - "127.0.0.1:8071:5341"
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seq:/data

volumes:
  db_data:
    driver: local
  redis:
    driver: local
  seq:
    driver: local
