version: '3.8'

name: arquivomate2

services:
  api:
    build:
      context: .
      dockerfile: src/ArquivoMate2.API/Dockerfile
    ports:
      - "5000:8081"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      USER_SECRETS_ID: bb5e46f1-5f35-4a18-b8ac-a5d3eef93c99
      ConnectionStrings__Default: "Host=db;Port=5432;Database=arquivomate;Username=postgres;Password=yourpassword"

  redis:
    image: redis/redis-stack:7.2.0-v8
    container_name: cache
    volumes:
       - redis:/data
       - redis:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
     - 6379:6379
     - 13333:8001

  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: arquivomate
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - db_data:/var/lib/postgresql/data

  meili:
    image: getmeili/meilisearch:v1.15.0-rc.0
    container_name: meili
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=supersecret
    volumes:
      - meili_data:/meili_data

volumes:
  db_data:
    driver: local
  redis:
    driver: local
  seq:
    driver: local
  meili_data:
    driver: local
