/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiMaintenanceDocumentEncryptionKeysGet$Params {

/**
 * Optional lower sequence bound (inclusive).
 */
  fromSequence?: number;

/**
 * Optional upper sequence bound (inclusive).
 */
  toSequence?: number;
}

export function apiMaintenanceDocumentEncryptionKeysGet(http: HttpClient, rootUrl: string, params?: ApiMaintenanceDocumentEncryptionKeysGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiMaintenanceDocumentEncryptionKeysGet.PATH, 'get');
  if (params) {
    rb.query('fromSequence', params.fromSequence, {});
    rb.query('toSequence', params.toSequence, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiMaintenanceDocumentEncryptionKeysGet.PATH = '/api/maintenance/document-encryption-keys';
