/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePartyRequest } from '../../models/create-party-request';
import { PartyDtoApiResponse } from '../../models/party-dto-api-response';

export interface ApiPartiesPost$Plain$Params {
      body?: CreatePartyRequest
}

export function apiPartiesPost$Plain(http: HttpClient, rootUrl: string, params?: ApiPartiesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PartyDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiPartiesPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartyDtoApiResponse>;
    })
  );
}

apiPartiesPost$Plain.PATH = '/api/parties';
