/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PartyDtoIEnumerableApiResponse } from '../../models/party-dto-i-enumerable-api-response';

export interface ApiPartiesGet$Plain$Params {
}

export function apiPartiesGet$Plain(http: HttpClient, rootUrl: string, params?: ApiPartiesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PartyDtoIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiPartiesGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartyDtoIEnumerableApiResponse>;
    })
  );
}

apiPartiesGet$Plain.PATH = '/api/parties';
