/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PartyDtoApiResponse } from '../../models/party-dto-api-response';
import { UpdatePartyRequest } from '../../models/update-party-request';

export interface ApiPartiesIdPut$Json$Params {
  id: string;
      body?: UpdatePartyRequest
}

export function apiPartiesIdPut$Json(http: HttpClient, rootUrl: string, params: ApiPartiesIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PartyDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiPartiesIdPut$Json.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartyDtoApiResponse>;
    })
  );
}

apiPartiesIdPut$Json.PATH = '/api/parties/{id}';
