/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateDocumentTypeRequest } from '../../models/create-document-type-request';
import { DocumentTypeDtoApiResponse } from '../../models/document-type-dto-api-response';

export interface ApiDocumentTypesPost$Json$Params {
      body?: CreateDocumentTypeRequest
}

export function apiDocumentTypesPost$Json(http: HttpClient, rootUrl: string, params?: ApiDocumentTypesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentTypeDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentTypesPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentTypeDtoApiResponse>;
    })
  );
}

apiDocumentTypesPost$Json.PATH = '/api/document-types';
