/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentTypeDtoApiResponse } from '../../models/document-type-dto-api-response';
import { UpdateDocumentTypeRequest } from '../../models/update-document-type-request';

export interface ApiDocumentTypesIdPut$Plain$Params {
  id: string;
      body?: UpdateDocumentTypeRequest
}

export function apiDocumentTypesIdPut$Plain(http: HttpClient, rootUrl: string, params: ApiDocumentTypesIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentTypeDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentTypesIdPut$Plain.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentTypeDtoApiResponse>;
    })
  );
}

apiDocumentTypesIdPut$Plain.PATH = '/api/document-types/{id}';
