/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignDocumentsRequest {
  collectionId?: string;
  documentIds?: Array<string> | null;
}
