/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CollectionDto {
  createdAtUtc?: string;
  documentCount?: number;
  id?: string;
  name?: string | null;
}
