/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CollectionDto } from '../models/collection-dto';
export interface CollectionDtoIEnumerableApiResponse {
  data?: Array<CollectionDto> | null;
  errorCode?: string | null;
  errors?: ({
[key: string]: Array<string>;
}) | null;
  message?: string | null;
  success?: boolean;
  timestamp?: string;
}
