/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDocumentTypeRequest {
  name: string;
  systemFeature?: string | null;
  systemFeatures?: Array<string> | null;
  userDefinedFunction?: string | null;
  userDefinedFunctions?: Array<string> | null;
}
