/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ShareAutomationScope } from '../models/share-automation-scope';
import { ShareTarget } from '../models/share-target';
export interface CreateShareAutomationRuleRequest {
  /** @deprecated */canEdit?: boolean;

  /**
   * Flags: subset of [Read, Edit, Delete]. Empty array = None. Accepts legacy formats: comma string or numeric.
   */
  permissions?: Array<'Read' | 'Edit' | 'Delete'>;
  scope?: ShareAutomationScope;
  target?: ShareTarget;
}
