/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentPermissions } from '../models/document-permissions';
import { ShareTarget } from '../models/share-target';
export interface CreateDocumentShareRequest {
  canEdit?: boolean;
  permissions?: DocumentPermissions;
  target?: ShareTarget;
}
