/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateShareGroupRequest {
  memberUserIds?: Array<string> | null;
  name?: string | null;
}
