/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentPermissions } from '../models/document-permissions';
import { ShareAutomationScope } from '../models/share-automation-scope';
import { ShareTarget } from '../models/share-target';
export interface CreateShareAutomationRuleRequest {
  canEdit?: boolean;
  permissions?: DocumentPermissions;
  scope?: ShareAutomationScope;
  target?: ShareTarget;
}
