/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentArtifact } from '../models/document-artifact';
export interface CreateShareRequest {
  artifact?: DocumentArtifact;
  documentId?: string;
  ttlMinutes?: number | null;
}
