/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrentUserDto } from '../models/current-user-dto';
export interface CurrentUserDtoApiResponse {
  data?: CurrentUserDto;
  errorCode?: string | null;
  errors?: ({
[key: string]: Array<string>;
}) | null;
  message?: string | null;
  success?: boolean;
  timestamp?: string;
}
