/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CurrentUserDto {
  apiKey?: string | null;
  createdAt?: string;
  id?: string | null;
  lastLoginAt?: string;
  name?: string | null;
}
