/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentNoteDto } from '../models/document-note-dto';
export interface DocumentNoteDtoIEnumerableApiResponse {
  data?: Array<DocumentNoteDto> | null;
  errorCode?: string | null;
  errors?: ({
[key: string]: Array<string>;
}) | null;
  message?: string | null;
  success?: boolean;
  timestamp?: string;
}
