/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProcessingStatus } from '../models/processing-status';
export interface DocumentStatusDto {
  documentId?: string;
  status?: ProcessingStatus;
  uploadedAt?: string;
}
