/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentListItemDto {
  accepted?: boolean;
  encrypted?: boolean;
  id?: string;
  keywords?: Array<string>;
  summary?: string;
  thumbnailPath?: string;
  title?: string;
  type?: string;
  uploadedAt?: string;
}
