/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentGroupingNode } from '../models/document-grouping-node';
export interface DocumentGroupingNodeIEnumerableApiResponse {
  data?: Array<DocumentGroupingNode> | null;
  errorCode?: string | null;
  errors?: ({
[key: string]: Array<string>;
}) | null;
  message?: string | null;
  success?: boolean;
  timestamp?: string;
}
