/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ShareTarget } from '../models/share-target';
export interface DocumentShareDto {
  /** @deprecated */canEdit?: boolean;
  documentId?: string;
  grantedBy?: string | null;
  id?: string;

  /**
   * Flags: subset of [Read, Edit, Delete]. Empty array = None. Accepts legacy formats: comma string or numeric.
   */
  permissions?: Array<'Read' | 'Edit' | 'Delete'>;
  sharedAt?: string;
  target?: ShareTarget;
}
