/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentStatsDto } from '../models/document-stats-dto';
export interface DocumentStatsDtoApiResponse {
  data?: DocumentStatsDto;
  errorCode?: string | null;
  errors?: ({
[key: string]: Array<string>;
}) | null;
  message?: string | null;
  success?: boolean;
  timestamp?: string;
}
