/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentEventDto {
  data?: string | null;
  eventType?: string | null;
  occurredOn?: string;
  userId?: string | null;
}
