/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentGroupingNode {
  count?: number;
  dimension?: string | null;
  hasChildren?: boolean;
  key?: string | null;
  label?: string | null;
}
