/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Represents the encryption mode applied to a document.
 */
export enum DocumentEncryptionType {
  Unencrypted = 'Unencrypted',
  S3 = 'S3',
  Custom = 'Custom',
}
