/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PartyListDto } from '../models/party-list-dto';
export interface DocumentListItemDto {
  accepted?: boolean;
  encrypted?: boolean;
  id?: string;
  keywords?: Array<string> | null;
  sender?: PartyListDto;
  summary?: string | null;
  thumbnailPath?: string | null;
  title?: string | null;
  type?: string | null;
  uploadedAt?: string;
}
