/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentListItemDto } from '../models/document-list-item-dto';
export interface DocumentListDto {
  currentPage?: number;
  documents?: Array<DocumentListItemDto> | null;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  isFirstPage?: boolean;
  isLastPage?: boolean;
  pageCount?: number;
  totalCount?: number;
}
