/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentStatsDto {
  characters?: number;
  documents?: number;
  facets: {
[key: string]: number;
};
  id?: string;
  notAccepted?: number;
}
