/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentAnswerCitationDto } from '../models/document-answer-citation-dto';
import { DocumentAnswerReferenceDto } from '../models/document-answer-reference-dto';
export interface DocumentAnswerDto {
  answer?: string | null;
  citations?: Array<DocumentAnswerCitationDto> | null;
  documentCount?: number | null;
  documents?: Array<DocumentAnswerReferenceDto> | null;
  model?: string | null;
}
