/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentNoteDto {
  createdAt?: string;
  documentId?: string;
  id?: string;
  text?: string | null;
  userId?: string | null;
}
