/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum DocumentArtifact {
  File = 'File',
  Preview = 'Preview',
  Thumb = 'Thumb',
  Metadata = 'Metadata',
  Archive = 'Archive'
}
