/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeatureProcessingState } from '../models/feature-processing-state';
export interface DocumentFeatureProcessingDto {
  attemptCount?: number;
  chatBotAvailable?: boolean;
  chatBotCallCount?: number;
  chatBotUsed?: boolean;
  completedAtUtc?: string | null;
  createdAtUtc?: string;
  documentId?: string;
  failedAtUtc?: string | null;
  featureKey?: string | null;
  id?: string;
  lastError?: string | null;
  startedAtUtc?: string | null;
  state?: FeatureProcessingState;
}
