/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentTypeDto {
  createdAtUtc?: string;
  id?: string;
  isAssignedToCurrentUser?: boolean;
  isLocked?: boolean;
  name?: string | null;
  systemFeatures?: Array<string> | null;
  updatedAtUtc?: string | null;
  userDefinedFunctions?: Array<string> | null;
}
