/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentEventDto } from '../models/document-event-dto';
import { PartyDto } from '../models/party-dto';
export interface DocumentDto {
  accepted?: boolean;
  acceptedAt?: string;
  archivePath?: string | null;
  chatBotClass?: string | null;
  chatBotModel?: string | null;
  content?: string | null;
  contentLength?: number;
  customerNumber?: string | null;
  encrypted?: boolean;
  filePath?: string | null;
  history?: Array<DocumentEventDto> | null;
  id?: string;
  invoiceNumber?: string | null;
  keywords?: Array<string> | null;
  language?: string | null;
  metadataPath?: string | null;
  notesCount?: number;
  previewPath?: string | null;
  processedAt?: string | null;
  sender?: PartyDto;
  summary?: string | null;
  thumbnailPath?: string | null;
  title?: string | null;
  totalPrice?: number | null;
  type?: string | null;
  uploadedAt?: string;
  userId?: string | null;
}
