/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentGroupingPathSegment } from '../models/document-grouping-path-segment';
export interface DocumentGroupingRequest {
  groups?: Array<string> | null;
  path?: Array<DocumentGroupingPathSegment> | null;
}
