/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DocumentAnswerReferenceDto {
  date?: string | null;
  documentId?: string;
  fileSizeBytes?: number | null;
  score?: number | null;
  summary?: string | null;
  title?: string | null;
}
