/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentEventDto } from '../models/document-event-dto';
export interface DocumentDto {
  accepted?: boolean;
  acceptedAt?: string;
  archivePath?: string;
  chatBotClass?: string;
  chatBotModel?: string;
  content?: string;
  contentLength?: number;
  customerNumber?: string;
  encrypted?: boolean;
  filePath?: string;
  history?: Array<DocumentEventDto>;
  id?: string;
  invoiceNumber?: string;
  keywords?: Array<string>;
  language?: string;
  metadataPath?: string;
  notesCount?: number;
  previewPath?: string;
  processedAt?: string | null;
  summary?: string;
  thumbnailPath?: string;
  title?: string;
  totalPrice?: number | null;
  type?: string;
  uploadedAt?: string;
  userId?: string;
}
