/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum EmailProviderType {
  Imap = 'IMAP',
  Pop3 = 'POP3',
  Exchange = 'Exchange',
  Null = 'Null'
}
