/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmailProviderType } from '../models/email-provider-type';
export interface EmailSettings {
  autoReconnect?: boolean;
  connectionTimeout?: number;
  createdAt?: string;
  defaultFolder?: string | null;
  displayName?: string | null;
  id?: string;
  isActive?: boolean;
  password?: string | null;
  port?: number;
  providerType?: EmailProviderType;
  server?: string | null;
  updatedAt?: string;
  useSsl?: boolean;
  userId?: string | null;
  username?: string | null;
}
