/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmailSortBy } from '../models/email-sort-by';
export interface EmailCriteriaDto {
  createdAt?: string;
  dateFrom?: string | null;
  dateTo?: string | null;
  description?: string | null;
  excludeFlags?: Array<string> | null;
  folderName?: string | null;
  fromContains?: string | null;
  hasAttachments?: boolean | null;
  id?: string;
  includeFlags?: Array<string> | null;
  isRead?: boolean | null;
  maxDaysBack?: number | null;
  maxResults?: number;
  name?: string | null;
  skip?: number;
  sortBy?: EmailSortBy;
  sortDescending?: boolean;
  subjectContains?: string | null;
  toContains?: string | null;
  updatedAt?: string;
}
