/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImportHistoryListItemDto {
  completedAt?: string | null;
  documentId?: string | null;
  errorMessage?: string | null;
  fileName?: string | null;
  id?: string;
  occurredOn?: string;
  source?: string | null;
  startedAt?: string;
  status?: string | null;
}
