/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportHistoryListDto } from '../models/import-history-list-dto';
export interface ImportHistoryListDtoApiResponse {
  data?: ImportHistoryListDto;
  errorCode?: string | null;
  errors?: ({
[key: string]: Array<string>;
}) | null;
  message?: string | null;
  success?: boolean;
  timestamp?: string;
}
