/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LabPivotTableDto } from '../models/lab-pivot-table-dto';
export interface LabPivotTableDtoApiResponse {
  data?: LabPivotTableDto;
  errorCode?: string | null;
  errors?: ({
[key: string]: Array<string>;
}) | null;
  message?: string | null;
  success?: boolean;
  timestamp?: string;
}
