/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PivotRowDto {
  parameter?: string | null;
  qualitativeByCol?: Array<string> | null;
  referenceComparatorByCol?: Array<string> | null;
  referenceFromByCol?: Array<number> | null;
  referenceToByCol?: Array<number> | null;
  unit?: string | null;
  valuesByCol?: Array<number> | null;
}
