/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ShareAutomationScope {
  AllDocuments = 'AllDocuments',
  FutureDocumentsOnly = 'FutureDocumentsOnly',
  Filtered = 'Filtered'
}
