/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ShareTargetType } from '../models/share-target-type';
export interface ShareTarget {
  identifier?: string;
  type?: ShareTargetType;
}
