/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShareGroupDto {
  id?: string | null;
  memberUserIds?: Array<string> | null;
  name?: string | null;
}
