/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ShareAutomationRuleDto } from '../models/share-automation-rule-dto';
export interface ShareAutomationRuleDtoApiResponse {
  data?: ShareAutomationRuleDto;
  errorCode?: string | null;
  errors?: ({
[key: string]: Array<string>;
}) | null;
  message?: string | null;
  success?: boolean;
  timestamp?: string;
}
