/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShareCreatedDto {
  artifact?: string | null;
  expiresAtUtc?: string;
  shareId?: string;
  url?: string | null;
}
