/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePartyRequest {
  city?: string | null;
  companyName?: string | null;
  firstName?: string | null;
  houseNumber?: string | null;
  id?: string;
  lastName?: string | null;
  postalCode?: string | null;
  street?: string | null;
}
