/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserApiKeyDto } from '../models/user-api-key-dto';
export interface UserApiKeyDtoApiResponse {
  data?: UserApiKeyDto;
  errorCode?: string | null;
  errors?: ({
[key: string]: Array<string>;
}) | null;
  message?: string | null;
  success?: boolean;
  timestamp?: string;
}
