/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  createdAt?: string;
  id?: string;
  lastLoginAt?: string;
  name?: string;
}
