/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiDocumentsDocumentIdNotesNoteIdDelete$Params {

/**
 * Identifier of the document that owns the note.
 */
  documentId: string;

/**
 * Identifier of the note to remove.
 */
  noteId: string;
}

export function apiDocumentsDocumentIdNotesNoteIdDelete(http: HttpClient, rootUrl: string, params: ApiDocumentsDocumentIdNotesNoteIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsDocumentIdNotesNoteIdDelete.PATH, 'delete');
  if (params) {
    rb.path('documentId', params.documentId, {});
    rb.path('noteId', params.noteId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiDocumentsDocumentIdNotesNoteIdDelete.PATH = '/api/documents/{documentId}/notes/{noteId}';
