/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateDocumentNoteRequest } from '../../models/create-document-note-request';
import { DocumentNoteDtoApiResponse } from '../../models/document-note-dto-api-response';

export interface ApiDocumentsDocumentIdNotesPost$Plain$Params {

/**
 * Identifier of the document that owns the note.
 */
  documentId: string;
  
    /**
     * Note payload containing the text that should be stored.
     */
    body?: CreateDocumentNoteRequest
}

export function apiDocumentsDocumentIdNotesPost$Plain(http: HttpClient, rootUrl: string, params: ApiDocumentsDocumentIdNotesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentNoteDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsDocumentIdNotesPost$Plain.PATH, 'post');
  if (params) {
    rb.path('documentId', params.documentId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentNoteDtoApiResponse>;
    })
  );
}

apiDocumentsDocumentIdNotesPost$Plain.PATH = '/api/documents/{documentId}/notes';
