/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentNoteDto } from '../../models/document-note-dto';

export interface ApiDocumentsDocumentIdNotesGet$Plain$Params {

/**
 * Identifier of the document whose notes should be listed.
 */
  documentId: string;

/**
 * Optional free text filter that narrows the result.
 */
  q?: string;
}

export function apiDocumentsDocumentIdNotesGet$Plain(http: HttpClient, rootUrl: string, params: ApiDocumentsDocumentIdNotesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentNoteDto>>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsDocumentIdNotesGet$Plain.PATH, 'get');
  if (params) {
    rb.path('documentId', params.documentId, {});
    rb.query('q', params.q, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DocumentNoteDto>>;
    })
  );
}

apiDocumentsDocumentIdNotesGet$Plain.PATH = '/api/documents/{documentId}/notes';
