/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentGroupingNode } from '../../models/document-grouping-node';
import { DocumentGroupingRequest } from '../../models/document-grouping-request';

export interface ApiDocumentsGroupingPost$Json$Params {
      body?: DocumentGroupingRequest
}

export function apiDocumentsGroupingPost$Json(http: HttpClient, rootUrl: string, params?: ApiDocumentsGroupingPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentGroupingNode>>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsGroupingPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DocumentGroupingNode>>;
    })
  );
}

apiDocumentsGroupingPost$Json.PATH = '/api/documents/grouping';
