/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentGroupingNodeIEnumerableApiResponse } from '../../models/document-grouping-node-i-enumerable-api-response';
import { DocumentGroupingRequest } from '../../models/document-grouping-request';

export interface ApiDocumentsGroupingPost$Plain$Params {
      body?: DocumentGroupingRequest
}

export function apiDocumentsGroupingPost$Plain(http: HttpClient, rootUrl: string, params?: ApiDocumentsGroupingPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentGroupingNodeIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsGroupingPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentGroupingNodeIEnumerableApiResponse>;
    })
  );
}

apiDocumentsGroupingPost$Plain.PATH = '/api/documents/grouping';
