/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateDocumentShareRequest } from '../../models/create-document-share-request';
import { DocumentShareDto } from '../../models/document-share-dto';

export interface ApiDocumentsDocumentIdSharesPost$Json$Params {
  documentId: string;
      body: CreateDocumentShareRequest
}

export function apiDocumentsDocumentIdSharesPost$Json(http: HttpClient, rootUrl: string, params: ApiDocumentsDocumentIdSharesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentShareDto>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsDocumentIdSharesPost$Json.PATH, 'post');
  if (params) {
    rb.path('documentId', params.documentId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentShareDto>;
    })
  );
}

apiDocumentsDocumentIdSharesPost$Json.PATH = '/api/documents/{documentId}/shares';
