/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiDocumentsDocumentIdSharesShareIdDelete$Params {
  documentId: string;
  shareId: string;
}

export function apiDocumentsDocumentIdSharesShareIdDelete(http: HttpClient, rootUrl: string, params: ApiDocumentsDocumentIdSharesShareIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsDocumentIdSharesShareIdDelete.PATH, 'delete');
  if (params) {
    rb.path('documentId', params.documentId, {});
    rb.path('shareId', params.shareId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiDocumentsDocumentIdSharesShareIdDelete.PATH = '/api/documents/{documentId}/shares/{shareId}';
