/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentShareDto } from '../../models/document-share-dto';

export interface ApiDocumentsDocumentIdSharesGet$Plain$Params {
  documentId: string;
}

export function apiDocumentsDocumentIdSharesGet$Plain(http: HttpClient, rootUrl: string, params: ApiDocumentsDocumentIdSharesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentShareDto>>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsDocumentIdSharesGet$Plain.PATH, 'get');
  if (params) {
    rb.path('documentId', params.documentId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DocumentShareDto>>;
    })
  );
}

apiDocumentsDocumentIdSharesGet$Plain.PATH = '/api/documents/{documentId}/shares';
