/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentDtoApiResponse } from '../../models/document-dto-api-response';
import { UpdateDocumentFieldsDto } from '../../models/update-document-fields-dto';

export interface ApiDocumentsIdUpdateFieldsPatch$Json$Params {
  id: string;
      body?: UpdateDocumentFieldsDto
}

export function apiDocumentsIdUpdateFieldsPatch$Json(http: HttpClient, rootUrl: string, params: ApiDocumentsIdUpdateFieldsPatch$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsIdUpdateFieldsPatch$Json.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentDtoApiResponse>;
    })
  );
}

apiDocumentsIdUpdateFieldsPatch$Json.PATH = '/api/documents/{id}/update-fields';
