/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentAnswerDtoApiResponse } from '../../models/document-answer-dto-api-response';
import { DocumentQuestionRequestDto } from '../../models/document-question-request-dto';

export interface ApiDocumentsIdChatPost$Json$Params {
  id: string;
      body?: DocumentQuestionRequestDto
}

export function apiDocumentsIdChatPost$Json(http: HttpClient, rootUrl: string, params: ApiDocumentsIdChatPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentAnswerDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsIdChatPost$Json.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentAnswerDtoApiResponse>;
    })
  );
}

apiDocumentsIdChatPost$Json.PATH = '/api/documents/{id}/chat';
