/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateShareRequest } from '../../models/create-share-request';
import { ShareCreatedDto } from '../../models/share-created-dto';

export interface ApiDocumentsSharePost$Plain$Params {
  
    /**
     * Request describing the document, artifact, and TTL.
     */
    body?: CreateShareRequest
}

export function apiDocumentsSharePost$Plain(http: HttpClient, rootUrl: string, params?: ApiDocumentsSharePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareCreatedDto>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsSharePost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShareCreatedDto>;
    })
  );
}

apiDocumentsSharePost$Plain.PATH = '/api/documents/share';
