/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentDto } from '../../models/document-dto';
import { UpdateDocumentFieldsDto } from '../../models/update-document-fields-dto';

export interface ApiDocumentsIdUpdateFieldsPatch$Plain$Params {

/**
 * Identifier of the document whose fields should be updated.
 */
  id: string;
  
    /**
     * Set of field updates to apply.
     */
    body?: UpdateDocumentFieldsDto
}

export function apiDocumentsIdUpdateFieldsPatch$Plain(http: HttpClient, rootUrl: string, params: ApiDocumentsIdUpdateFieldsPatch$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDto>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsIdUpdateFieldsPatch$Plain.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentDto>;
    })
  );
}

apiDocumentsIdUpdateFieldsPatch$Plain.PATH = '/api/documents/{id}/update-fields';
