/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentStatsDtoApiResponse } from '../../models/document-stats-dto-api-response';

export interface ApiDocumentsStatsGet$Plain$Params {
}

export function apiDocumentsStatsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiDocumentsStatsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentStatsDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsStatsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentStatsDtoApiResponse>;
    })
  );
}

apiDocumentsStatsGet$Plain.PATH = '/api/documents/stats';
