/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateShareRequest } from '../../models/create-share-request';
import { ShareCreatedDtoApiResponse } from '../../models/share-created-dto-api-response';

export interface ApiDocumentsSharePost$Json$Params {
      body?: CreateShareRequest
}

export function apiDocumentsSharePost$Json(http: HttpClient, rootUrl: string, params?: ApiDocumentsSharePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareCreatedDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsSharePost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShareCreatedDtoApiResponse>;
    })
  );
}

apiDocumentsSharePost$Json.PATH = '/api/documents/share';
