/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExternalShareIEnumerableApiResponse } from '../../models/external-share-i-enumerable-api-response';

export interface ApiDocumentsIdSharesGet$Plain$Params {
  id: string;
}

export function apiDocumentsIdSharesGet$Plain(http: HttpClient, rootUrl: string, params: ApiDocumentsIdSharesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ExternalShareIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsIdSharesGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExternalShareIEnumerableApiResponse>;
    })
  );
}

apiDocumentsIdSharesGet$Plain.PATH = '/api/documents/{id}/shares';
