/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentAnswerDtoApiResponse } from '../../models/document-answer-dto-api-response';
import { DocumentQuestionRequestDto } from '../../models/document-question-request-dto';

export interface ApiDocumentsChatPost$Plain$Params {
      body?: DocumentQuestionRequestDto
}

export function apiDocumentsChatPost$Plain(http: HttpClient, rootUrl: string, params?: ApiDocumentsChatPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentAnswerDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDocumentsChatPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentAnswerDtoApiResponse>;
    })
  );
}

apiDocumentsChatPost$Plain.PATH = '/api/documents/chat';
