/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiDeliveryDocumentIdArtifactGet } from '../fn/delivery/api-delivery-document-id-artifact-get';
import { ApiDeliveryDocumentIdArtifactGet$Params } from '../fn/delivery/api-delivery-document-id-artifact-get';

@Injectable({ providedIn: 'root' })
export class DeliveryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiDeliveryDocumentIdArtifactGet()` */
  static readonly ApiDeliveryDocumentIdArtifactGetPath = '/api/delivery/{documentId}/{artifact}';

  /**
   * Delivers an encrypted artifact for a document when a valid access token is supplied.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDeliveryDocumentIdArtifactGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDeliveryDocumentIdArtifactGet$Response(params: ApiDeliveryDocumentIdArtifactGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiDeliveryDocumentIdArtifactGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Delivers an encrypted artifact for a document when a valid access token is supplied.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDeliveryDocumentIdArtifactGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDeliveryDocumentIdArtifactGet(params: ApiDeliveryDocumentIdArtifactGet$Params, context?: HttpContext): Observable<void> {
    return this.apiDeliveryDocumentIdArtifactGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
