/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiDocumentsChatPost$Json } from '../fn/documents/api-documents-chat-post-json';
import { ApiDocumentsChatPost$Json$Params } from '../fn/documents/api-documents-chat-post-json';
import { apiDocumentsChatPost$Plain } from '../fn/documents/api-documents-chat-post-plain';
import { ApiDocumentsChatPost$Plain$Params } from '../fn/documents/api-documents-chat-post-plain';
import { apiDocumentsGet$Json } from '../fn/documents/api-documents-get-json';
import { ApiDocumentsGet$Json$Params } from '../fn/documents/api-documents-get-json';
import { apiDocumentsGet$Plain } from '../fn/documents/api-documents-get-plain';
import { ApiDocumentsGet$Plain$Params } from '../fn/documents/api-documents-get-plain';
import { apiDocumentsIdChatPost$Json } from '../fn/documents/api-documents-id-chat-post-json';
import { ApiDocumentsIdChatPost$Json$Params } from '../fn/documents/api-documents-id-chat-post-json';
import { apiDocumentsIdChatPost$Plain } from '../fn/documents/api-documents-id-chat-post-plain';
import { ApiDocumentsIdChatPost$Plain$Params } from '../fn/documents/api-documents-id-chat-post-plain';
import { apiDocumentsIdGet$Json } from '../fn/documents/api-documents-id-get-json';
import { ApiDocumentsIdGet$Json$Params } from '../fn/documents/api-documents-id-get-json';
import { apiDocumentsIdGet$Plain } from '../fn/documents/api-documents-id-get-plain';
import { ApiDocumentsIdGet$Plain$Params } from '../fn/documents/api-documents-id-get-plain';
import { apiDocumentsIdUpdateFieldsPatch$Json } from '../fn/documents/api-documents-id-update-fields-patch-json';
import { ApiDocumentsIdUpdateFieldsPatch$Json$Params } from '../fn/documents/api-documents-id-update-fields-patch-json';
import { apiDocumentsIdUpdateFieldsPatch$Plain } from '../fn/documents/api-documents-id-update-fields-patch-plain';
import { ApiDocumentsIdUpdateFieldsPatch$Plain$Params } from '../fn/documents/api-documents-id-update-fields-patch-plain';
import { apiDocumentsPost$Json } from '../fn/documents/api-documents-post-json';
import { ApiDocumentsPost$Json$Params } from '../fn/documents/api-documents-post-json';
import { apiDocumentsPost$Plain } from '../fn/documents/api-documents-post-plain';
import { ApiDocumentsPost$Plain$Params } from '../fn/documents/api-documents-post-plain';
import { apiDocumentsSharePost$Json } from '../fn/documents/api-documents-share-post-json';
import { ApiDocumentsSharePost$Json$Params } from '../fn/documents/api-documents-share-post-json';
import { apiDocumentsSharePost$Plain } from '../fn/documents/api-documents-share-post-plain';
import { ApiDocumentsSharePost$Plain$Params } from '../fn/documents/api-documents-share-post-plain';
import { apiDocumentsStatsGet$Json } from '../fn/documents/api-documents-stats-get-json';
import { ApiDocumentsStatsGet$Json$Params } from '../fn/documents/api-documents-stats-get-json';
import { apiDocumentsStatsGet$Plain } from '../fn/documents/api-documents-stats-get-plain';
import { ApiDocumentsStatsGet$Plain$Params } from '../fn/documents/api-documents-stats-get-plain';
import { DocumentAnswerDtoApiResponse } from '../models/document-answer-dto-api-response';
import { DocumentDtoApiResponse } from '../models/document-dto-api-response';
import { DocumentListDtoApiResponse } from '../models/document-list-dto-api-response';
import { DocumentStatsDtoApiResponse } from '../models/document-stats-dto-api-response';
import { GuidApiResponse } from '../models/guid-api-response';
import { ShareCreatedDtoApiResponse } from '../models/share-created-dto-api-response';


/**
 * Provides endpoints for managing document metadata, importing files, and retrieving document content.
 */
@Injectable({ providedIn: 'root' })
export class DocumentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiDocumentsGet()` */
  static readonly ApiDocumentsGetPath = '/api/documents';

  /**
   * Retrieves a paginated document list using optional full-text search, filtering, and sorting criteria.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsGet$Plain$Response(params?: ApiDocumentsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentListDtoApiResponse>> {
    return apiDocumentsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a paginated document list using optional full-text search, filtering, and sorting criteria.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsGet$Plain(params?: ApiDocumentsGet$Plain$Params, context?: HttpContext): Observable<DocumentListDtoApiResponse> {
    return this.apiDocumentsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentListDtoApiResponse>): DocumentListDtoApiResponse => r.body)
    );
  }

  /**
   * Retrieves a paginated document list using optional full-text search, filtering, and sorting criteria.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsGet$Json$Response(params?: ApiDocumentsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentListDtoApiResponse>> {
    return apiDocumentsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a paginated document list using optional full-text search, filtering, and sorting criteria.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsGet$Json(params?: ApiDocumentsGet$Json$Params, context?: HttpContext): Observable<DocumentListDtoApiResponse> {
    return this.apiDocumentsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentListDtoApiResponse>): DocumentListDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiDocumentsPost()` */
  static readonly ApiDocumentsPostPath = '/api/documents';

  /**
   * Uploads a new document, starts its import stream, and schedules the background processing workflow.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsPost$Plain()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiDocumentsPost$Plain$Response(params?: ApiDocumentsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<GuidApiResponse>> {
    return apiDocumentsPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Uploads a new document, starts its import stream, and schedules the background processing workflow.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsPost$Plain$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiDocumentsPost$Plain(params?: ApiDocumentsPost$Plain$Params, context?: HttpContext): Observable<GuidApiResponse> {
    return this.apiDocumentsPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<GuidApiResponse>): GuidApiResponse => r.body)
    );
  }

  /**
   * Uploads a new document, starts its import stream, and schedules the background processing workflow.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsPost$Json()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiDocumentsPost$Json$Response(params?: ApiDocumentsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GuidApiResponse>> {
    return apiDocumentsPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Uploads a new document, starts its import stream, and schedules the background processing workflow.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsPost$Json$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiDocumentsPost$Json(params?: ApiDocumentsPost$Json$Params, context?: HttpContext): Observable<GuidApiResponse> {
    return this.apiDocumentsPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<GuidApiResponse>): GuidApiResponse => r.body)
    );
  }

  /** Path part for operation `apiDocumentsIdUpdateFieldsPatch()` */
  static readonly ApiDocumentsIdUpdateFieldsPatchPath = '/api/documents/{id}/update-fields';

  /**
   * Updates mutable document metadata fields and refreshes the search index when necessary.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsIdUpdateFieldsPatch$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsIdUpdateFieldsPatch$Plain$Response(params: ApiDocumentsIdUpdateFieldsPatch$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDtoApiResponse>> {
    return apiDocumentsIdUpdateFieldsPatch$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates mutable document metadata fields and refreshes the search index when necessary.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsIdUpdateFieldsPatch$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsIdUpdateFieldsPatch$Plain(params: ApiDocumentsIdUpdateFieldsPatch$Plain$Params, context?: HttpContext): Observable<DocumentDtoApiResponse> {
    return this.apiDocumentsIdUpdateFieldsPatch$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentDtoApiResponse>): DocumentDtoApiResponse => r.body)
    );
  }

  /**
   * Updates mutable document metadata fields and refreshes the search index when necessary.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsIdUpdateFieldsPatch$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsIdUpdateFieldsPatch$Json$Response(params: ApiDocumentsIdUpdateFieldsPatch$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDtoApiResponse>> {
    return apiDocumentsIdUpdateFieldsPatch$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates mutable document metadata fields and refreshes the search index when necessary.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsIdUpdateFieldsPatch$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsIdUpdateFieldsPatch$Json(params: ApiDocumentsIdUpdateFieldsPatch$Json$Params, context?: HttpContext): Observable<DocumentDtoApiResponse> {
    return this.apiDocumentsIdUpdateFieldsPatch$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentDtoApiResponse>): DocumentDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiDocumentsStatsGet()` */
  static readonly ApiDocumentsStatsGetPath = '/api/documents/stats';

  /**
   * Returns aggregate document statistics and search facets for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsStatsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsStatsGet$Plain$Response(params?: ApiDocumentsStatsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentStatsDtoApiResponse>> {
    return apiDocumentsStatsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Returns aggregate document statistics and search facets for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsStatsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsStatsGet$Plain(params?: ApiDocumentsStatsGet$Plain$Params, context?: HttpContext): Observable<DocumentStatsDtoApiResponse> {
    return this.apiDocumentsStatsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentStatsDtoApiResponse>): DocumentStatsDtoApiResponse => r.body)
    );
  }

  /**
   * Returns aggregate document statistics and search facets for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsStatsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsStatsGet$Json$Response(params?: ApiDocumentsStatsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentStatsDtoApiResponse>> {
    return apiDocumentsStatsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Returns aggregate document statistics and search facets for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsStatsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsStatsGet$Json(params?: ApiDocumentsStatsGet$Json$Params, context?: HttpContext): Observable<DocumentStatsDtoApiResponse> {
    return this.apiDocumentsStatsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentStatsDtoApiResponse>): DocumentStatsDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiDocumentsIdGet()` */
  static readonly ApiDocumentsIdGetPath = '/api/documents/{id}';

  /**
   * Retrieves a single document including its projection and event history.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsIdGet$Plain$Response(params: ApiDocumentsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDtoApiResponse>> {
    return apiDocumentsIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a single document including its projection and event history.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsIdGet$Plain(params: ApiDocumentsIdGet$Plain$Params, context?: HttpContext): Observable<DocumentDtoApiResponse> {
    return this.apiDocumentsIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentDtoApiResponse>): DocumentDtoApiResponse => r.body)
    );
  }

  /**
   * Retrieves a single document including its projection and event history.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsIdGet$Json$Response(params: ApiDocumentsIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentDtoApiResponse>> {
    return apiDocumentsIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a single document including its projection and event history.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiDocumentsIdGet$Json(params: ApiDocumentsIdGet$Json$Params, context?: HttpContext): Observable<DocumentDtoApiResponse> {
    return this.apiDocumentsIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentDtoApiResponse>): DocumentDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiDocumentsIdChatPost()` */
  static readonly ApiDocumentsIdChatPostPath = '/api/documents/{id}/chat';

  /**
   * Sends a user's natural language question to the configured chatbot and returns the generated answer.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsIdChatPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsIdChatPost$Plain$Response(params: ApiDocumentsIdChatPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentAnswerDtoApiResponse>> {
    return apiDocumentsIdChatPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Sends a user's natural language question to the configured chatbot and returns the generated answer.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsIdChatPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsIdChatPost$Plain(params: ApiDocumentsIdChatPost$Plain$Params, context?: HttpContext): Observable<DocumentAnswerDtoApiResponse> {
    return this.apiDocumentsIdChatPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentAnswerDtoApiResponse>): DocumentAnswerDtoApiResponse => r.body)
    );
  }

  /**
   * Sends a user's natural language question to the configured chatbot and returns the generated answer.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsIdChatPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsIdChatPost$Json$Response(params: ApiDocumentsIdChatPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentAnswerDtoApiResponse>> {
    return apiDocumentsIdChatPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Sends a user's natural language question to the configured chatbot and returns the generated answer.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsIdChatPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsIdChatPost$Json(params: ApiDocumentsIdChatPost$Json$Params, context?: HttpContext): Observable<DocumentAnswerDtoApiResponse> {
    return this.apiDocumentsIdChatPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentAnswerDtoApiResponse>): DocumentAnswerDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiDocumentsChatPost()` */
  static readonly ApiDocumentsChatPostPath = '/api/documents/chat';

  /**
   * Sends a question about the user's entire document catalogue to the chatbot.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsChatPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsChatPost$Plain$Response(params?: ApiDocumentsChatPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentAnswerDtoApiResponse>> {
    return apiDocumentsChatPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Sends a question about the user's entire document catalogue to the chatbot.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsChatPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsChatPost$Plain(params?: ApiDocumentsChatPost$Plain$Params, context?: HttpContext): Observable<DocumentAnswerDtoApiResponse> {
    return this.apiDocumentsChatPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentAnswerDtoApiResponse>): DocumentAnswerDtoApiResponse => r.body)
    );
  }

  /**
   * Sends a question about the user's entire document catalogue to the chatbot.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsChatPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsChatPost$Json$Response(params?: ApiDocumentsChatPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentAnswerDtoApiResponse>> {
    return apiDocumentsChatPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Sends a question about the user's entire document catalogue to the chatbot.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsChatPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsChatPost$Json(params?: ApiDocumentsChatPost$Json$Params, context?: HttpContext): Observable<DocumentAnswerDtoApiResponse> {
    return this.apiDocumentsChatPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DocumentAnswerDtoApiResponse>): DocumentAnswerDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiDocumentsSharePost()` */
  static readonly ApiDocumentsSharePostPath = '/api/documents/share';

  /**
   * Creates a time-limited external share link for a document artifact.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsSharePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsSharePost$Plain$Response(params?: ApiDocumentsSharePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareCreatedDtoApiResponse>> {
    return apiDocumentsSharePost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a time-limited external share link for a document artifact.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsSharePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsSharePost$Plain(params?: ApiDocumentsSharePost$Plain$Params, context?: HttpContext): Observable<ShareCreatedDtoApiResponse> {
    return this.apiDocumentsSharePost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShareCreatedDtoApiResponse>): ShareCreatedDtoApiResponse => r.body)
    );
  }

  /**
   * Creates a time-limited external share link for a document artifact.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiDocumentsSharePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsSharePost$Json$Response(params?: ApiDocumentsSharePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareCreatedDtoApiResponse>> {
    return apiDocumentsSharePost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a time-limited external share link for a document artifact.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiDocumentsSharePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiDocumentsSharePost$Json(params?: ApiDocumentsSharePost$Json$Params, context?: HttpContext): Observable<ShareCreatedDtoApiResponse> {
    return this.apiDocumentsSharePost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShareCreatedDtoApiResponse>): ShareCreatedDtoApiResponse => r.body)
    );
  }

}
