/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiEmailCountGet$Json } from '../fn/email/api-email-count-get-json';
import { ApiEmailCountGet$Json$Params } from '../fn/email/api-email-count-get-json';
import { apiEmailCountGet$Plain } from '../fn/email/api-email-count-get-plain';
import { ApiEmailCountGet$Plain$Params } from '../fn/email/api-email-count-get-plain';
import { apiEmailCriteriaDelete$Json } from '../fn/email/api-email-criteria-delete-json';
import { ApiEmailCriteriaDelete$Json$Params } from '../fn/email/api-email-criteria-delete-json';
import { apiEmailCriteriaDelete$Plain } from '../fn/email/api-email-criteria-delete-plain';
import { ApiEmailCriteriaDelete$Plain$Params } from '../fn/email/api-email-criteria-delete-plain';
import { apiEmailCriteriaGet$Json } from '../fn/email/api-email-criteria-get-json';
import { ApiEmailCriteriaGet$Json$Params } from '../fn/email/api-email-criteria-get-json';
import { apiEmailCriteriaGet$Plain } from '../fn/email/api-email-criteria-get-plain';
import { ApiEmailCriteriaGet$Plain$Params } from '../fn/email/api-email-criteria-get-plain';
import { apiEmailCriteriaPost$Json } from '../fn/email/api-email-criteria-post-json';
import { ApiEmailCriteriaPost$Json$Params } from '../fn/email/api-email-criteria-post-json';
import { apiEmailCriteriaPost$Plain } from '../fn/email/api-email-criteria-post-plain';
import { ApiEmailCriteriaPost$Plain$Params } from '../fn/email/api-email-criteria-post-plain';
import { apiEmailSettingsDelete$Json } from '../fn/email/api-email-settings-delete-json';
import { ApiEmailSettingsDelete$Json$Params } from '../fn/email/api-email-settings-delete-json';
import { apiEmailSettingsDelete$Plain } from '../fn/email/api-email-settings-delete-plain';
import { ApiEmailSettingsDelete$Plain$Params } from '../fn/email/api-email-settings-delete-plain';
import { apiEmailSettingsGet$Json } from '../fn/email/api-email-settings-get-json';
import { ApiEmailSettingsGet$Json$Params } from '../fn/email/api-email-settings-get-json';
import { apiEmailSettingsGet$Plain } from '../fn/email/api-email-settings-get-plain';
import { ApiEmailSettingsGet$Plain$Params } from '../fn/email/api-email-settings-get-plain';
import { apiEmailSettingsPost$Json } from '../fn/email/api-email-settings-post-json';
import { ApiEmailSettingsPost$Json$Params } from '../fn/email/api-email-settings-post-json';
import { apiEmailSettingsPost$Plain } from '../fn/email/api-email-settings-post-plain';
import { ApiEmailSettingsPost$Plain$Params } from '../fn/email/api-email-settings-post-plain';
import { apiEmailTestConnectionPost$Json } from '../fn/email/api-email-test-connection-post-json';
import { ApiEmailTestConnectionPost$Json$Params } from '../fn/email/api-email-test-connection-post-json';
import { apiEmailTestConnectionPost$Plain } from '../fn/email/api-email-test-connection-post-plain';
import { ApiEmailTestConnectionPost$Plain$Params } from '../fn/email/api-email-test-connection-post-plain';
import { EmailCriteriaDtoApiResponse } from '../models/email-criteria-dto-api-response';
import { Int32ApiResponse } from '../models/int-32-api-response';
import { ObjectApiResponse } from '../models/object-api-response';

@Injectable({ providedIn: 'root' })
export class EmailService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiEmailCountGet()` */
  static readonly ApiEmailCountGetPath = '/api/Email/count';

  /**
   * Gets the total count of emails in the mailbox.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailCountGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCountGet$Plain$Response(params?: ApiEmailCountGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Int32ApiResponse>> {
    return apiEmailCountGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the total count of emails in the mailbox.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailCountGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCountGet$Plain(params?: ApiEmailCountGet$Plain$Params, context?: HttpContext): Observable<Int32ApiResponse> {
    return this.apiEmailCountGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Int32ApiResponse>): Int32ApiResponse => r.body)
    );
  }

  /**
   * Gets the total count of emails in the mailbox.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailCountGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCountGet$Json$Response(params?: ApiEmailCountGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Int32ApiResponse>> {
    return apiEmailCountGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the total count of emails in the mailbox.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailCountGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCountGet$Json(params?: ApiEmailCountGet$Json$Params, context?: HttpContext): Observable<Int32ApiResponse> {
    return this.apiEmailCountGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Int32ApiResponse>): Int32ApiResponse => r.body)
    );
  }

  /** Path part for operation `apiEmailTestConnectionPost()` */
  static readonly ApiEmailTestConnectionPostPath = '/api/Email/test-connection';

  /**
   * Tests the email connection with current settings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailTestConnectionPost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailTestConnectionPost$Plain$Response(params?: ApiEmailTestConnectionPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
    return apiEmailTestConnectionPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Tests the email connection with current settings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailTestConnectionPost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailTestConnectionPost$Plain(params?: ApiEmailTestConnectionPost$Plain$Params, context?: HttpContext): Observable<ObjectApiResponse> {
    return this.apiEmailTestConnectionPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectApiResponse>): ObjectApiResponse => r.body)
    );
  }

  /**
   * Tests the email connection with current settings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailTestConnectionPost$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailTestConnectionPost$Json$Response(params?: ApiEmailTestConnectionPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
    return apiEmailTestConnectionPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Tests the email connection with current settings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailTestConnectionPost$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailTestConnectionPost$Json(params?: ApiEmailTestConnectionPost$Json$Params, context?: HttpContext): Observable<ObjectApiResponse> {
    return this.apiEmailTestConnectionPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectApiResponse>): ObjectApiResponse => r.body)
    );
  }

  /** Path part for operation `apiEmailSettingsGet()` */
  static readonly ApiEmailSettingsGetPath = '/api/Email/settings';

  /**
   * Gets the current user's email settings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailSettingsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailSettingsGet$Plain$Response(params?: ApiEmailSettingsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
    return apiEmailSettingsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the current user's email settings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailSettingsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailSettingsGet$Plain(params?: ApiEmailSettingsGet$Plain$Params, context?: HttpContext): Observable<ObjectApiResponse> {
    return this.apiEmailSettingsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectApiResponse>): ObjectApiResponse => r.body)
    );
  }

  /**
   * Gets the current user's email settings.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailSettingsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailSettingsGet$Json$Response(params?: ApiEmailSettingsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
    return apiEmailSettingsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the current user's email settings.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailSettingsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailSettingsGet$Json(params?: ApiEmailSettingsGet$Json$Params, context?: HttpContext): Observable<ObjectApiResponse> {
    return this.apiEmailSettingsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectApiResponse>): ObjectApiResponse => r.body)
    );
  }

  /** Path part for operation `apiEmailSettingsPost()` */
  static readonly ApiEmailSettingsPostPath = '/api/Email/settings';

  /**
   * Saves or updates email settings for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailSettingsPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEmailSettingsPost$Plain$Response(params?: ApiEmailSettingsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
    return apiEmailSettingsPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Saves or updates email settings for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailSettingsPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEmailSettingsPost$Plain(params?: ApiEmailSettingsPost$Plain$Params, context?: HttpContext): Observable<ObjectApiResponse> {
    return this.apiEmailSettingsPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectApiResponse>): ObjectApiResponse => r.body)
    );
  }

  /**
   * Saves or updates email settings for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailSettingsPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEmailSettingsPost$Json$Response(params?: ApiEmailSettingsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
    return apiEmailSettingsPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Saves or updates email settings for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailSettingsPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEmailSettingsPost$Json(params?: ApiEmailSettingsPost$Json$Params, context?: HttpContext): Observable<ObjectApiResponse> {
    return this.apiEmailSettingsPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectApiResponse>): ObjectApiResponse => r.body)
    );
  }

  /** Path part for operation `apiEmailSettingsDelete()` */
  static readonly ApiEmailSettingsDeletePath = '/api/Email/settings';

  /**
   * Deletes email settings for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailSettingsDelete$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailSettingsDelete$Plain$Response(params?: ApiEmailSettingsDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
    return apiEmailSettingsDelete$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Deletes email settings for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailSettingsDelete$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailSettingsDelete$Plain(params?: ApiEmailSettingsDelete$Plain$Params, context?: HttpContext): Observable<ObjectApiResponse> {
    return this.apiEmailSettingsDelete$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectApiResponse>): ObjectApiResponse => r.body)
    );
  }

  /**
   * Deletes email settings for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailSettingsDelete$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailSettingsDelete$Json$Response(params?: ApiEmailSettingsDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
    return apiEmailSettingsDelete$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Deletes email settings for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailSettingsDelete$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailSettingsDelete$Json(params?: ApiEmailSettingsDelete$Json$Params, context?: HttpContext): Observable<ObjectApiResponse> {
    return this.apiEmailSettingsDelete$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectApiResponse>): ObjectApiResponse => r.body)
    );
  }

  /** Path part for operation `apiEmailCriteriaGet()` */
  static readonly ApiEmailCriteriaGetPath = '/api/Email/criteria';

  /**
   * Gets the email criteria for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailCriteriaGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCriteriaGet$Plain$Response(params?: ApiEmailCriteriaGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailCriteriaDtoApiResponse>> {
    return apiEmailCriteriaGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the email criteria for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailCriteriaGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCriteriaGet$Plain(params?: ApiEmailCriteriaGet$Plain$Params, context?: HttpContext): Observable<EmailCriteriaDtoApiResponse> {
    return this.apiEmailCriteriaGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailCriteriaDtoApiResponse>): EmailCriteriaDtoApiResponse => r.body)
    );
  }

  /**
   * Gets the email criteria for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailCriteriaGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCriteriaGet$Json$Response(params?: ApiEmailCriteriaGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailCriteriaDtoApiResponse>> {
    return apiEmailCriteriaGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the email criteria for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailCriteriaGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCriteriaGet$Json(params?: ApiEmailCriteriaGet$Json$Params, context?: HttpContext): Observable<EmailCriteriaDtoApiResponse> {
    return this.apiEmailCriteriaGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailCriteriaDtoApiResponse>): EmailCriteriaDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiEmailCriteriaPost()` */
  static readonly ApiEmailCriteriaPostPath = '/api/Email/criteria';

  /**
   * Saves (creates or updates) email criteria for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailCriteriaPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEmailCriteriaPost$Plain$Response(params?: ApiEmailCriteriaPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailCriteriaDtoApiResponse>> {
    return apiEmailCriteriaPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Saves (creates or updates) email criteria for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailCriteriaPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEmailCriteriaPost$Plain(params?: ApiEmailCriteriaPost$Plain$Params, context?: HttpContext): Observable<EmailCriteriaDtoApiResponse> {
    return this.apiEmailCriteriaPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailCriteriaDtoApiResponse>): EmailCriteriaDtoApiResponse => r.body)
    );
  }

  /**
   * Saves (creates or updates) email criteria for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailCriteriaPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEmailCriteriaPost$Json$Response(params?: ApiEmailCriteriaPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailCriteriaDtoApiResponse>> {
    return apiEmailCriteriaPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Saves (creates or updates) email criteria for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailCriteriaPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiEmailCriteriaPost$Json(params?: ApiEmailCriteriaPost$Json$Params, context?: HttpContext): Observable<EmailCriteriaDtoApiResponse> {
    return this.apiEmailCriteriaPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailCriteriaDtoApiResponse>): EmailCriteriaDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiEmailCriteriaDelete()` */
  static readonly ApiEmailCriteriaDeletePath = '/api/Email/criteria';

  /**
   * Deletes email criteria for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailCriteriaDelete$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCriteriaDelete$Plain$Response(params?: ApiEmailCriteriaDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
    return apiEmailCriteriaDelete$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Deletes email criteria for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailCriteriaDelete$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCriteriaDelete$Plain(params?: ApiEmailCriteriaDelete$Plain$Params, context?: HttpContext): Observable<ObjectApiResponse> {
    return this.apiEmailCriteriaDelete$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectApiResponse>): ObjectApiResponse => r.body)
    );
  }

  /**
   * Deletes email criteria for the current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmailCriteriaDelete$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCriteriaDelete$Json$Response(params?: ApiEmailCriteriaDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
    return apiEmailCriteriaDelete$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Deletes email criteria for the current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmailCriteriaDelete$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmailCriteriaDelete$Json(params?: ApiEmailCriteriaDelete$Json$Params, context?: HttpContext): Observable<ObjectApiResponse> {
    return this.apiEmailCriteriaDelete$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectApiResponse>): ObjectApiResponse => r.body)
    );
  }

}
