/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiHistoryCompletedCountGet } from '../fn/import-history/api-history-completed-count-get';
import { ApiHistoryCompletedCountGet$Params } from '../fn/import-history/api-history-completed-count-get';
import { apiHistoryCompletedGet$Json } from '../fn/import-history/api-history-completed-get-json';
import { ApiHistoryCompletedGet$Json$Params } from '../fn/import-history/api-history-completed-get-json';
import { apiHistoryCompletedGet$Plain } from '../fn/import-history/api-history-completed-get-plain';
import { ApiHistoryCompletedGet$Plain$Params } from '../fn/import-history/api-history-completed-get-plain';
import { apiHistoryFailedCountGet } from '../fn/import-history/api-history-failed-count-get';
import { ApiHistoryFailedCountGet$Params } from '../fn/import-history/api-history-failed-count-get';
import { apiHistoryFailedGet$Json } from '../fn/import-history/api-history-failed-get-json';
import { ApiHistoryFailedGet$Json$Params } from '../fn/import-history/api-history-failed-get-json';
import { apiHistoryFailedGet$Plain } from '../fn/import-history/api-history-failed-get-plain';
import { ApiHistoryFailedGet$Plain$Params } from '../fn/import-history/api-history-failed-get-plain';
import { apiHistoryGet } from '../fn/import-history/api-history-get';
import { ApiHistoryGet$Params } from '../fn/import-history/api-history-get';
import { apiHistoryInprogressCountGet } from '../fn/import-history/api-history-inprogress-count-get';
import { ApiHistoryInprogressCountGet$Params } from '../fn/import-history/api-history-inprogress-count-get';
import { apiHistoryInprogressGet$Json } from '../fn/import-history/api-history-inprogress-get-json';
import { ApiHistoryInprogressGet$Json$Params } from '../fn/import-history/api-history-inprogress-get-json';
import { apiHistoryInprogressGet$Plain } from '../fn/import-history/api-history-inprogress-get-plain';
import { ApiHistoryInprogressGet$Plain$Params } from '../fn/import-history/api-history-inprogress-get-plain';
import { apiHistoryPendingCountGet } from '../fn/import-history/api-history-pending-count-get';
import { ApiHistoryPendingCountGet$Params } from '../fn/import-history/api-history-pending-count-get';
import { apiHistoryPendingGet$Json } from '../fn/import-history/api-history-pending-get-json';
import { ApiHistoryPendingGet$Json$Params } from '../fn/import-history/api-history-pending-get-json';
import { apiHistoryPendingGet$Plain } from '../fn/import-history/api-history-pending-get-plain';
import { ApiHistoryPendingGet$Plain$Params } from '../fn/import-history/api-history-pending-get-plain';
import { ImportHistoryListDto } from '../models/import-history-list-dto';

@Injectable({ providedIn: 'root' })
export class ImportHistoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiHistoryGet()` */
  static readonly ApiHistoryGetPath = '/api/history';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryGet$Response(params?: ApiHistoryGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiHistoryGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryGet(params?: ApiHistoryGet$Params, context?: HttpContext): Observable<void> {
    return this.apiHistoryGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiHistoryInprogressCountGet()` */
  static readonly ApiHistoryInprogressCountGetPath = '/api/history/inprogress/count';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryInprogressCountGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryInprogressCountGet$Response(params?: ApiHistoryInprogressCountGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiHistoryInprogressCountGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryInprogressCountGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryInprogressCountGet(params?: ApiHistoryInprogressCountGet$Params, context?: HttpContext): Observable<void> {
    return this.apiHistoryInprogressCountGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiHistoryInprogressGet()` */
  static readonly ApiHistoryInprogressGetPath = '/api/history/inprogress';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryInprogressGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryInprogressGet$Plain$Response(params?: ApiHistoryInprogressGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportHistoryListDto>> {
    return apiHistoryInprogressGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryInprogressGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryInprogressGet$Plain(params?: ApiHistoryInprogressGet$Plain$Params, context?: HttpContext): Observable<ImportHistoryListDto> {
    return this.apiHistoryInprogressGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ImportHistoryListDto>): ImportHistoryListDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryInprogressGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryInprogressGet$Json$Response(params?: ApiHistoryInprogressGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportHistoryListDto>> {
    return apiHistoryInprogressGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryInprogressGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryInprogressGet$Json(params?: ApiHistoryInprogressGet$Json$Params, context?: HttpContext): Observable<ImportHistoryListDto> {
    return this.apiHistoryInprogressGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ImportHistoryListDto>): ImportHistoryListDto => r.body)
    );
  }

  /** Path part for operation `apiHistoryPendingCountGet()` */
  static readonly ApiHistoryPendingCountGetPath = '/api/history/pending/count';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryPendingCountGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryPendingCountGet$Response(params?: ApiHistoryPendingCountGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiHistoryPendingCountGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryPendingCountGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryPendingCountGet(params?: ApiHistoryPendingCountGet$Params, context?: HttpContext): Observable<void> {
    return this.apiHistoryPendingCountGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiHistoryPendingGet()` */
  static readonly ApiHistoryPendingGetPath = '/api/history/pending';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryPendingGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryPendingGet$Plain$Response(params?: ApiHistoryPendingGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportHistoryListDto>> {
    return apiHistoryPendingGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryPendingGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryPendingGet$Plain(params?: ApiHistoryPendingGet$Plain$Params, context?: HttpContext): Observable<ImportHistoryListDto> {
    return this.apiHistoryPendingGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ImportHistoryListDto>): ImportHistoryListDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryPendingGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryPendingGet$Json$Response(params?: ApiHistoryPendingGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportHistoryListDto>> {
    return apiHistoryPendingGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryPendingGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryPendingGet$Json(params?: ApiHistoryPendingGet$Json$Params, context?: HttpContext): Observable<ImportHistoryListDto> {
    return this.apiHistoryPendingGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ImportHistoryListDto>): ImportHistoryListDto => r.body)
    );
  }

  /** Path part for operation `apiHistoryCompletedCountGet()` */
  static readonly ApiHistoryCompletedCountGetPath = '/api/history/completed/count';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryCompletedCountGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryCompletedCountGet$Response(params?: ApiHistoryCompletedCountGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiHistoryCompletedCountGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryCompletedCountGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryCompletedCountGet(params?: ApiHistoryCompletedCountGet$Params, context?: HttpContext): Observable<void> {
    return this.apiHistoryCompletedCountGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiHistoryCompletedGet()` */
  static readonly ApiHistoryCompletedGetPath = '/api/history/completed';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryCompletedGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryCompletedGet$Plain$Response(params?: ApiHistoryCompletedGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportHistoryListDto>> {
    return apiHistoryCompletedGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryCompletedGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryCompletedGet$Plain(params?: ApiHistoryCompletedGet$Plain$Params, context?: HttpContext): Observable<ImportHistoryListDto> {
    return this.apiHistoryCompletedGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ImportHistoryListDto>): ImportHistoryListDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryCompletedGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryCompletedGet$Json$Response(params?: ApiHistoryCompletedGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportHistoryListDto>> {
    return apiHistoryCompletedGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryCompletedGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryCompletedGet$Json(params?: ApiHistoryCompletedGet$Json$Params, context?: HttpContext): Observable<ImportHistoryListDto> {
    return this.apiHistoryCompletedGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ImportHistoryListDto>): ImportHistoryListDto => r.body)
    );
  }

  /** Path part for operation `apiHistoryFailedCountGet()` */
  static readonly ApiHistoryFailedCountGetPath = '/api/history/failed/count';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryFailedCountGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryFailedCountGet$Response(params?: ApiHistoryFailedCountGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiHistoryFailedCountGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryFailedCountGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryFailedCountGet(params?: ApiHistoryFailedCountGet$Params, context?: HttpContext): Observable<void> {
    return this.apiHistoryFailedCountGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiHistoryFailedGet()` */
  static readonly ApiHistoryFailedGetPath = '/api/history/failed';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryFailedGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryFailedGet$Plain$Response(params?: ApiHistoryFailedGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportHistoryListDto>> {
    return apiHistoryFailedGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryFailedGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryFailedGet$Plain(params?: ApiHistoryFailedGet$Plain$Params, context?: HttpContext): Observable<ImportHistoryListDto> {
    return this.apiHistoryFailedGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ImportHistoryListDto>): ImportHistoryListDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHistoryFailedGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryFailedGet$Json$Response(params?: ApiHistoryFailedGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportHistoryListDto>> {
    return apiHistoryFailedGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHistoryFailedGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHistoryFailedGet$Json(params?: ApiHistoryFailedGet$Json$Params, context?: HttpContext): Observable<ImportHistoryListDto> {
    return this.apiHistoryFailedGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ImportHistoryListDto>): ImportHistoryListDto => r.body)
    );
  }

}
