/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiShareShareIdGet } from '../fn/public-share/api-share-share-id-get';
import { ApiShareShareIdGet$Params } from '../fn/public-share/api-share-share-id-get';

@Injectable({ providedIn: 'root' })
export class PublicShareService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiShareShareIdGet()` */
  static readonly ApiShareShareIdGetPath = '/api/share/{shareId}';

  /**
   * Streams a shared document artifact to anonymous callers with a valid share token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShareShareIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShareShareIdGet$Response(params: ApiShareShareIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiShareShareIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Streams a shared document artifact to anonymous callers with a valid share token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShareShareIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShareShareIdGet(params: ApiShareShareIdGet$Params, context?: HttpContext): Observable<void> {
    return this.apiShareShareIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
