/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiSystemFeaturesGet } from '../fn/system/api-system-features-get';
import { ApiSystemFeaturesGet$Params } from '../fn/system/api-system-features-get';

@Injectable({ providedIn: 'root' })
export class SystemService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiSystemFeaturesGet()` */
  static readonly ApiSystemFeaturesGetPath = '/api/system/features';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSystemFeaturesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSystemFeaturesGet$Response(params?: ApiSystemFeaturesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiSystemFeaturesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSystemFeaturesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSystemFeaturesGet(params?: ApiSystemFeaturesGet$Params, context?: HttpContext): Observable<void> {
    return this.apiSystemFeaturesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
