/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUsersApiKeyPost$Json } from '../fn/users/api-users-api-key-post-json';
import { ApiUsersApiKeyPost$Json$Params } from '../fn/users/api-users-api-key-post-json';
import { apiUsersApiKeyPost$Plain } from '../fn/users/api-users-api-key-post-plain';
import { ApiUsersApiKeyPost$Plain$Params } from '../fn/users/api-users-api-key-post-plain';
import { apiUsersLoginPost$Json } from '../fn/users/api-users-login-post-json';
import { ApiUsersLoginPost$Json$Params } from '../fn/users/api-users-login-post-json';
import { apiUsersLoginPost$Plain } from '../fn/users/api-users-login-post-plain';
import { ApiUsersLoginPost$Plain$Params } from '../fn/users/api-users-login-post-plain';
import { apiUsersMeGet$Json } from '../fn/users/api-users-me-get-json';
import { ApiUsersMeGet$Json$Params } from '../fn/users/api-users-me-get-json';
import { apiUsersMeGet$Plain } from '../fn/users/api-users-me-get-plain';
import { ApiUsersMeGet$Plain$Params } from '../fn/users/api-users-me-get-plain';
import { apiUsersOthersGet$Json } from '../fn/users/api-users-others-get-json';
import { ApiUsersOthersGet$Json$Params } from '../fn/users/api-users-others-get-json';
import { apiUsersOthersGet$Plain } from '../fn/users/api-users-others-get-plain';
import { ApiUsersOthersGet$Plain$Params } from '../fn/users/api-users-others-get-plain';
import { CurrentUserDtoApiResponse } from '../models/current-user-dto-api-response';
import { UserApiKeyDtoApiResponse } from '../models/user-api-key-dto-api-response';
import { UserDtoApiResponse } from '../models/user-dto-api-response';
import { UserDtoIEnumerableApiResponse } from '../models/user-dto-i-enumerable-api-response';

@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUsersMeGet()` */
  static readonly ApiUsersMeGetPath = '/api/users/me';

  /**
   * Returns the current authenticated user profile without updating timestamps.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersMeGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersMeGet$Plain$Response(params?: ApiUsersMeGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentUserDtoApiResponse>> {
    return apiUsersMeGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Returns the current authenticated user profile without updating timestamps.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersMeGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersMeGet$Plain(params?: ApiUsersMeGet$Plain$Params, context?: HttpContext): Observable<CurrentUserDtoApiResponse> {
    return this.apiUsersMeGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<CurrentUserDtoApiResponse>): CurrentUserDtoApiResponse => r.body)
    );
  }

  /**
   * Returns the current authenticated user profile without updating timestamps.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersMeGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersMeGet$Json$Response(params?: ApiUsersMeGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentUserDtoApiResponse>> {
    return apiUsersMeGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Returns the current authenticated user profile without updating timestamps.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersMeGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersMeGet$Json(params?: ApiUsersMeGet$Json$Params, context?: HttpContext): Observable<CurrentUserDtoApiResponse> {
    return this.apiUsersMeGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<CurrentUserDtoApiResponse>): CurrentUserDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiUsersLoginPost()` */
  static readonly ApiUsersLoginPostPath = '/api/users/login';

  /**
   * Synchronises the authenticated user with the application store.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersLoginPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsersLoginPost$Plain$Response(params?: ApiUsersLoginPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDtoApiResponse>> {
    return apiUsersLoginPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Synchronises the authenticated user with the application store.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersLoginPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsersLoginPost$Plain(params?: ApiUsersLoginPost$Plain$Params, context?: HttpContext): Observable<UserDtoApiResponse> {
    return this.apiUsersLoginPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDtoApiResponse>): UserDtoApiResponse => r.body)
    );
  }

  /**
   * Synchronises the authenticated user with the application store.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersLoginPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsersLoginPost$Json$Response(params?: ApiUsersLoginPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDtoApiResponse>> {
    return apiUsersLoginPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Synchronises the authenticated user with the application store.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersLoginPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsersLoginPost$Json(params?: ApiUsersLoginPost$Json$Params, context?: HttpContext): Observable<UserDtoApiResponse> {
    return this.apiUsersLoginPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDtoApiResponse>): UserDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiUsersOthersGet()` */
  static readonly ApiUsersOthersGetPath = '/api/users/others';

  /**
   * Returns all other users (for sharing dialogs etc.).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersOthersGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersOthersGet$Plain$Response(params?: ApiUsersOthersGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDtoIEnumerableApiResponse>> {
    return apiUsersOthersGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Returns all other users (for sharing dialogs etc.).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersOthersGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersOthersGet$Plain(params?: ApiUsersOthersGet$Plain$Params, context?: HttpContext): Observable<UserDtoIEnumerableApiResponse> {
    return this.apiUsersOthersGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDtoIEnumerableApiResponse>): UserDtoIEnumerableApiResponse => r.body)
    );
  }

  /**
   * Returns all other users (for sharing dialogs etc.).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersOthersGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersOthersGet$Json$Response(params?: ApiUsersOthersGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDtoIEnumerableApiResponse>> {
    return apiUsersOthersGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Returns all other users (for sharing dialogs etc.).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersOthersGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersOthersGet$Json(params?: ApiUsersOthersGet$Json$Params, context?: HttpContext): Observable<UserDtoIEnumerableApiResponse> {
    return this.apiUsersOthersGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDtoIEnumerableApiResponse>): UserDtoIEnumerableApiResponse => r.body)
    );
  }

  /** Path part for operation `apiUsersApiKeyPost()` */
  static readonly ApiUsersApiKeyPostPath = '/api/users/api-key';

  /**
   * Generates a new API key for the authenticated user and stores it with the profile.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersApiKeyPost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersApiKeyPost$Plain$Response(params?: ApiUsersApiKeyPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserApiKeyDtoApiResponse>> {
    return apiUsersApiKeyPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Generates a new API key for the authenticated user and stores it with the profile.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersApiKeyPost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersApiKeyPost$Plain(params?: ApiUsersApiKeyPost$Plain$Params, context?: HttpContext): Observable<UserApiKeyDtoApiResponse> {
    return this.apiUsersApiKeyPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserApiKeyDtoApiResponse>): UserApiKeyDtoApiResponse => r.body)
    );
  }

  /**
   * Generates a new API key for the authenticated user and stores it with the profile.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersApiKeyPost$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersApiKeyPost$Json$Response(params?: ApiUsersApiKeyPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserApiKeyDtoApiResponse>> {
    return apiUsersApiKeyPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Generates a new API key for the authenticated user and stores it with the profile.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersApiKeyPost$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersApiKeyPost$Json(params?: ApiUsersApiKeyPost$Json$Params, context?: HttpContext): Observable<UserApiKeyDtoApiResponse> {
    return this.apiUsersApiKeyPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserApiKeyDtoApiResponse>): UserApiKeyDtoApiResponse => r.body)
    );
  }

}
