/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUsersLoginPost$Json } from '../fn/users/api-users-login-post-json';
import { ApiUsersLoginPost$Json$Params } from '../fn/users/api-users-login-post-json';
import { apiUsersLoginPost$Plain } from '../fn/users/api-users-login-post-plain';
import { ApiUsersLoginPost$Plain$Params } from '../fn/users/api-users-login-post-plain';
import { apiUsersOthersGet$Json } from '../fn/users/api-users-others-get-json';
import { ApiUsersOthersGet$Json$Params } from '../fn/users/api-users-others-get-json';
import { apiUsersOthersGet$Plain } from '../fn/users/api-users-others-get-plain';
import { ApiUsersOthersGet$Plain$Params } from '../fn/users/api-users-others-get-plain';
import { UserDto } from '../models/user-dto';

@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUsersLoginPost()` */
  static readonly ApiUsersLoginPostPath = '/api/users/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersLoginPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsersLoginPost$Plain$Response(params: ApiUsersLoginPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return apiUsersLoginPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersLoginPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsersLoginPost$Plain(params: ApiUsersLoginPost$Plain$Params, context?: HttpContext): Observable<UserDto> {
    return this.apiUsersLoginPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersLoginPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsersLoginPost$Json$Response(params: ApiUsersLoginPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return apiUsersLoginPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersLoginPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsersLoginPost$Json(params: ApiUsersLoginPost$Json$Params, context?: HttpContext): Observable<UserDto> {
    return this.apiUsersLoginPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `apiUsersOthersGet()` */
  static readonly ApiUsersOthersGetPath = '/api/users/others';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersOthersGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersOthersGet$Plain$Response(params?: ApiUsersOthersGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserDto>>> {
    return apiUsersOthersGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersOthersGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersOthersGet$Plain(params?: ApiUsersOthersGet$Plain$Params, context?: HttpContext): Observable<Array<UserDto>> {
    return this.apiUsersOthersGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserDto>>): Array<UserDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersOthersGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersOthersGet$Json$Response(params?: ApiUsersOthersGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserDto>>> {
    return apiUsersOthersGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersOthersGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersOthersGet$Json(params?: ApiUsersOthersGet$Json$Params, context?: HttpContext): Observable<Array<UserDto>> {
    return this.apiUsersOthersGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserDto>>): Array<UserDto> => r.body)
    );
  }

}
