/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { CollectionsService } from './services/collections.service';
import { DeliveryService } from './services/delivery.service';
import { DocumentGroupingService } from './services/document-grouping.service';
import { DocumentNotesService } from './services/document-notes.service';
import { DocumentsService } from './services/documents.service';
import { DocumentSharesService } from './services/document-shares.service';
import { EmailService } from './services/email.service';
import { ImportHistoryService } from './services/import-history.service';
import { IngestionService } from './services/ingestion.service';
import { MaintenanceService } from './services/maintenance.service';
import { PartiesService } from './services/parties.service';
import { PublicShareService } from './services/public-share.service';
import { ShareAutomationRulesService } from './services/share-automation-rules.service';
import { ShareGroupsService } from './services/share-groups.service';
import { UsersService } from './services/users.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    CollectionsService,
    DeliveryService,
    DocumentGroupingService,
    DocumentNotesService,
    DocumentsService,
    DocumentSharesService,
    EmailService,
    ImportHistoryService,
    IngestionService,
    MaintenanceService,
    PartiesService,
    PublicShareService,
    ShareAutomationRulesService,
    ShareGroupsService,
    UsersService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
