/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CreateDocumentNoteRequest } from './models/create-document-note-request';
export type { DocumentDto } from './models/document-dto';
export type { DocumentEventDto } from './models/document-event-dto';
export type { DocumentListDto } from './models/document-list-dto';
export type { DocumentListItemDto } from './models/document-list-item-dto';
export type { DocumentNoteDto } from './models/document-note-dto';
export type { DocumentStatsDto } from './models/document-stats-dto';
export type { EmailCriteriaDto } from './models/email-criteria-dto';
export type { EmailProviderType } from './models/email-provider-type';
export type { EmailSettings } from './models/email-settings';
export type { EmailSortBy } from './models/email-sort-by';
export type { ImportHistoryListDto } from './models/import-history-list-dto';
export type { ImportHistoryListItemDto } from './models/import-history-list-item-dto';
export type { ProblemDetails } from './models/problem-details';
export type { SaveEmailCriteriaRequest } from './models/save-email-criteria-request';
export type { SaveEmailSettingsRequest } from './models/save-email-settings-request';
export type { UpdateDocumentFieldsDto } from './models/update-document-fields-dto';
