/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AssignDocumentsRequest } from './models/assign-documents-request';
export type { AssignResultDto } from './models/assign-result-dto';
export type { CollectionDto } from './models/collection-dto';
export type { CreateCollectionRequest } from './models/create-collection-request';
export type { CreateDocumentNoteRequest } from './models/create-document-note-request';
export type { CreateDocumentShareRequest } from './models/create-document-share-request';
export type { CreateShareAutomationRuleRequest } from './models/create-share-automation-rule-request';
export type { CreateShareGroupRequest } from './models/create-share-group-request';
export type { CreateShareRequest } from './models/create-share-request';
export type { CurrentUserDto } from './models/current-user-dto';
export { DocumentArtifact } from './models/document-artifact';
export type { DocumentDto } from './models/document-dto';
export type { DocumentEventDto } from './models/document-event-dto';
export type { DocumentGroupingNode } from './models/document-grouping-node';
export type { DocumentGroupingPathSegment } from './models/document-grouping-path-segment';
export type { DocumentGroupingRequest } from './models/document-grouping-request';
export type { DocumentListDto } from './models/document-list-dto';
export type { DocumentListItemDto } from './models/document-list-item-dto';
export type { DocumentNoteDto } from './models/document-note-dto';
export { DocumentProcessingStatus } from './models/document-processing-status';
export type { DocumentShareDto } from './models/document-share-dto';
export type { DocumentStatsDto } from './models/document-stats-dto';
export type { EmailCriteriaDto } from './models/email-criteria-dto';
export { EmailProviderType } from './models/email-provider-type';
export type { EmailSettings } from './models/email-settings';
export { EmailSortBy } from './models/email-sort-by';
export type { ImportHistoryListDto } from './models/import-history-list-dto';
export type { ImportHistoryListItemDto } from './models/import-history-list-item-dto';
export type { PartyDto } from './models/party-dto';
export type { PartyListDto } from './models/party-list-dto';
export type { ProblemDetails } from './models/problem-details';
export type { SaveEmailCriteriaRequest } from './models/save-email-criteria-request';
export type { SaveEmailSettingsRequest } from './models/save-email-settings-request';
export type { ShareAutomationRuleDto } from './models/share-automation-rule-dto';
export { ShareAutomationScope } from './models/share-automation-scope';
export type { ShareCreatedDto } from './models/share-created-dto';
export type { ShareGroupDto } from './models/share-group-dto';
export type { ShareTarget } from './models/share-target';
export type { UpdateCollectionRequest } from './models/update-collection-request';
export type { UpdateDocumentFieldsDto } from './models/update-document-fields-dto';
export type { UpdateShareGroupRequest } from './models/update-share-group-request';
export type { UpsertUserRequest } from './models/upsert-user-request';
export type { UserApiKeyDto } from './models/user-api-key-dto';
export type { UserDto } from './models/user-dto';
