/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailCriteriaDto } from '../../models/email-criteria-dto';
import { SaveEmailCriteriaRequest } from '../../models/save-email-criteria-request';

export interface ApiEmailCriteriaPost$Plain$Params {
      body: SaveEmailCriteriaRequest
}

export function apiEmailCriteriaPost$Plain(http: HttpClient, rootUrl: string, params: ApiEmailCriteriaPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailCriteriaDto>> {
  const rb = new RequestBuilder(rootUrl, apiEmailCriteriaPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailCriteriaDto>;
    })
  );
}

apiEmailCriteriaPost$Plain.PATH = '/api/Email/criteria';
