/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectApiResponse } from '../../models/object-api-response';

export interface ApiEmailSettingsDelete$Plain$Params {
}

export function apiEmailSettingsDelete$Plain(http: HttpClient, rootUrl: string, params?: ApiEmailSettingsDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiEmailSettingsDelete$Plain.PATH, 'delete');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectApiResponse>;
    })
  );
}

apiEmailSettingsDelete$Plain.PATH = '/api/Email/settings';
