/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConnectionTestResultDtoApiResponse } from '../../models/connection-test-result-dto-api-response';

export interface ApiEmailTestConnectionPost$Plain$Params {
}

export function apiEmailTestConnectionPost$Plain(http: HttpClient, rootUrl: string, params?: ApiEmailTestConnectionPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ConnectionTestResultDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiEmailTestConnectionPost$Plain.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConnectionTestResultDtoApiResponse>;
    })
  );
}

apiEmailTestConnectionPost$Plain.PATH = '/api/Email/test-connection';
