/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResponseMessageDtoApiResponse } from '../../models/response-message-dto-api-response';

export interface ApiEmailCriteriaDelete$Json$Params {
}

export function apiEmailCriteriaDelete$Json(http: HttpClient, rootUrl: string, params?: ApiEmailCriteriaDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponseMessageDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiEmailCriteriaDelete$Json.PATH, 'delete');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResponseMessageDtoApiResponse>;
    })
  );
}

apiEmailCriteriaDelete$Json.PATH = '/api/Email/criteria';
