/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailCriteriaDtoApiResponse } from '../../models/email-criteria-dto-api-response';

export interface ApiEmailCriteriaGet$Plain$Params {
}

export function apiEmailCriteriaGet$Plain(http: HttpClient, rootUrl: string, params?: ApiEmailCriteriaGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailCriteriaDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiEmailCriteriaGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailCriteriaDtoApiResponse>;
    })
  );
}

apiEmailCriteriaGet$Plain.PATH = '/api/Email/criteria';
