/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailSettings } from '../../models/email-settings';

export interface ApiEmailSettingsGet$Plain$Params {
}

export function apiEmailSettingsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiEmailSettingsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailSettings>> {
  const rb = new RequestBuilder(rootUrl, apiEmailSettingsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailSettings>;
    })
  );
}

apiEmailSettingsGet$Plain.PATH = '/api/Email/settings';
