/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailCriteriaDtoApiResponse } from '../../models/email-criteria-dto-api-response';

export interface ApiEmailCriteriaGet$Json$Params {
}

export function apiEmailCriteriaGet$Json(http: HttpClient, rootUrl: string, params?: ApiEmailCriteriaGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailCriteriaDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiEmailCriteriaGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailCriteriaDtoApiResponse>;
    })
  );
}

apiEmailCriteriaGet$Json.PATH = '/api/Email/criteria';
