/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectApiResponse } from '../../models/object-api-response';
import { SaveEmailSettingsRequest } from '../../models/save-email-settings-request';

export interface ApiEmailSettingsPost$Plain$Params {
      body?: SaveEmailSettingsRequest
}

export function apiEmailSettingsPost$Plain(http: HttpClient, rootUrl: string, params?: ApiEmailSettingsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiEmailSettingsPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectApiResponse>;
    })
  );
}

apiEmailSettingsPost$Plain.PATH = '/api/Email/settings';
