/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpsertUserRequest } from '../../models/upsert-user-request';
import { UserDtoApiResponse } from '../../models/user-dto-api-response';

export interface ApiUsersLoginPost$Plain$Params {
      body?: UpsertUserRequest
}

export function apiUsersLoginPost$Plain(http: HttpClient, rootUrl: string, params?: ApiUsersLoginPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUsersLoginPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserDtoApiResponse>;
    })
  );
}

apiUsersLoginPost$Plain.PATH = '/api/users/login';
