/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserApiKeyDtoApiResponse } from '../../models/user-api-key-dto-api-response';

export interface ApiUsersApiKeyPost$Plain$Params {
}

export function apiUsersApiKeyPost$Plain(http: HttpClient, rootUrl: string, params?: ApiUsersApiKeyPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserApiKeyDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUsersApiKeyPost$Plain.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserApiKeyDtoApiResponse>;
    })
  );
}

apiUsersApiKeyPost$Plain.PATH = '/api/users/api-key';
