/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserApiKeyDto } from '../../models/user-api-key-dto';

export interface ApiUsersApiKeyPost$Json$Params {
}

export function apiUsersApiKeyPost$Json(http: HttpClient, rootUrl: string, params?: ApiUsersApiKeyPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserApiKeyDto>> {
  const rb = new RequestBuilder(rootUrl, apiUsersApiKeyPost$Json.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserApiKeyDto>;
    })
  );
}

apiUsersApiKeyPost$Json.PATH = '/api/users/api-key';
