/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserDtoIEnumerableApiResponse } from '../../models/user-dto-i-enumerable-api-response';

export interface ApiUsersOthersGet$Json$Params {
}

export function apiUsersOthersGet$Json(http: HttpClient, rootUrl: string, params?: ApiUsersOthersGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDtoIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUsersOthersGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserDtoIEnumerableApiResponse>;
    })
  );
}

apiUsersOthersGet$Json.PATH = '/api/users/others';
