/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CurrentUserDtoApiResponse } from '../../models/current-user-dto-api-response';

export interface ApiUsersMeGet$Json$Params {
}

export function apiUsersMeGet$Json(http: HttpClient, rootUrl: string, params?: ApiUsersMeGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentUserDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUsersMeGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CurrentUserDtoApiResponse>;
    })
  );
}

apiUsersMeGet$Json.PATH = '/api/users/me';
