/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StringApiResponse } from '../../models/string-api-response';

export interface ApiIngestionFilesPost$Plain$Params {
      body?: {
'File'?: Blob;
}
}

export function apiIngestionFilesPost$Plain(http: HttpClient, rootUrl: string, params?: ApiIngestionFilesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<StringApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiIngestionFilesPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StringApiResponse>;
    })
  );
}

apiIngestionFilesPost$Plain.PATH = '/api/ingestion/files';
