/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShareAutomationRuleDto } from '../../models/share-automation-rule-dto';

export interface ApiShareAutomationRulesGet$Json$Params {
}

export function apiShareAutomationRulesGet$Json(http: HttpClient, rootUrl: string, params?: ApiShareAutomationRulesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShareAutomationRuleDto>>> {
  const rb = new RequestBuilder(rootUrl, apiShareAutomationRulesGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ShareAutomationRuleDto>>;
    })
  );
}

apiShareAutomationRulesGet$Json.PATH = '/api/share-automation-rules';
