/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateShareAutomationRuleRequest } from '../../models/create-share-automation-rule-request';
import { ShareAutomationRuleDto } from '../../models/share-automation-rule-dto';

export interface ApiShareAutomationRulesPost$Plain$Params {
      body: CreateShareAutomationRuleRequest
}

export function apiShareAutomationRulesPost$Plain(http: HttpClient, rootUrl: string, params: ApiShareAutomationRulesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareAutomationRuleDto>> {
  const rb = new RequestBuilder(rootUrl, apiShareAutomationRulesPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShareAutomationRuleDto>;
    })
  );
}

apiShareAutomationRulesPost$Plain.PATH = '/api/share-automation-rules';
