/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CollectionDtoApiResponse } from '../../models/collection-dto-api-response';
import { UpdateCollectionRequest } from '../../models/update-collection-request';

export interface ApiCollectionsIdPut$Plain$Params {
  id: string;
      body?: UpdateCollectionRequest
}

export function apiCollectionsIdPut$Plain(http: HttpClient, rootUrl: string, params: ApiCollectionsIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CollectionDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCollectionsIdPut$Plain.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CollectionDtoApiResponse>;
    })
  );
}

apiCollectionsIdPut$Plain.PATH = '/api/collections/{id}';
