/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CollectionDtoApiResponse } from '../../models/collection-dto-api-response';
import { CreateCollectionRequest } from '../../models/create-collection-request';

export interface ApiCollectionsPost$Json$Params {
      body?: CreateCollectionRequest
}

export function apiCollectionsPost$Json(http: HttpClient, rootUrl: string, params?: ApiCollectionsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CollectionDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCollectionsPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CollectionDtoApiResponse>;
    })
  );
}

apiCollectionsPost$Json.PATH = '/api/collections';
