/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CollectionDtoApiResponse } from '../../models/collection-dto-api-response';

export interface ApiCollectionsIdGet$Plain$Params {
  id: string;
}

export function apiCollectionsIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiCollectionsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CollectionDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCollectionsIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CollectionDtoApiResponse>;
    })
  );
}

apiCollectionsIdGet$Plain.PATH = '/api/collections/{id}';
