/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignDocumentsRequest } from '../../models/assign-documents-request';
import { AssignResultDtoApiResponse } from '../../models/assign-result-dto-api-response';

export interface ApiCollectionsIdAssignPost$Json$Params {
  id: string;
      body?: AssignDocumentsRequest
}

export function apiCollectionsIdAssignPost$Json(http: HttpClient, rootUrl: string, params: ApiCollectionsIdAssignPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<AssignResultDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCollectionsIdAssignPost$Json.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AssignResultDtoApiResponse>;
    })
  );
}

apiCollectionsIdAssignPost$Json.PATH = '/api/collections/{id}/assign';
