/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShareGroupDto } from '../../models/share-group-dto';

export interface ApiShareGroupsGet$Plain$Params {
}

export function apiShareGroupsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiShareGroupsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ShareGroupDto>>> {
  const rb = new RequestBuilder(rootUrl, apiShareGroupsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ShareGroupDto>>;
    })
  );
}

apiShareGroupsGet$Plain.PATH = '/api/share-groups';
