/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateShareGroupRequest } from '../../models/create-share-group-request';
import { ShareGroupDto } from '../../models/share-group-dto';

export interface ApiShareGroupsPost$Plain$Params {
  
    /**
     * Group definition including its name and members.
     */
    body?: CreateShareGroupRequest
}

export function apiShareGroupsPost$Plain(http: HttpClient, rootUrl: string, params?: ApiShareGroupsPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareGroupDto>> {
  const rb = new RequestBuilder(rootUrl, apiShareGroupsPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShareGroupDto>;
    })
  );
}

apiShareGroupsPost$Plain.PATH = '/api/share-groups';
