/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShareGroupDto } from '../../models/share-group-dto';

export interface ApiShareGroupsGroupIdGet$Json$Params {
  groupId: string;
}

export function apiShareGroupsGroupIdGet$Json(http: HttpClient, rootUrl: string, params: ApiShareGroupsGroupIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ShareGroupDto>> {
  const rb = new RequestBuilder(rootUrl, apiShareGroupsGroupIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('groupId', params.groupId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShareGroupDto>;
    })
  );
}

apiShareGroupsGroupIdGet$Json.PATH = '/api/share-groups/{groupId}';
